name: MagicAntics
main: net.undergroundantics.magicantics.plugin.MagicAntics
version: 0.4
api-version: 1.13
authors: [Isaac, Dxyze]
commands:
   spellscroll:
      description: Gives spell scroll.
      usage: /spellscroll <spell> [player]
      permission: magicantics.spawn.scroll
      permission-message: You don't have permission to do this.
   spellbook:
      description: Gives spell book.
      usage: /spellbook <spell> [player]
      permission: magicantics.spawn.book
      permission-message: You don't have permission to do this.
   spelltome:
      description: Gives spell tome.
      usage: /spelltome [player]
      permission: magicantics.spawn.tome
      permission-message: You don't have permission to do this.
   spellknowledge:
      description: Adds or removes the players knowledge of spells
      usage: /spellknowledge <player> [clear | add <spell> | remove <spell>]
      permission: magicantics.admin
      permission-message: You don't have permission to do this.